
// This file was autogenerated by the genConstants.js script.
// DO NOT MODIFY.

export const CommandNames = {
    "GENERATE": [
        "generate",
        "g",
        "gen"
    ],
    "GENERATE_COMPONENT": [
        "component",
        "c",
        "comp"
    ]
};
