const { promises: fs } = require("fs")
const { join } = require("path");
const commandsJson = require("../src/services/commands/commands.json");

const commandNames = {};

for (const key of Object.keys(commandsJson)) {
    const parent = commandsJson[key];
    const child = Object.values(parent)[Object.values(parent).length - 1];

    for (const a of parent.aliases) {
        if (!commandNames[key.toUpperCase()]) commandNames[key.toUpperCase()] = [key];
        commandNames[key.toUpperCase()].push(a);
    }

    for (const a of child.aliases) {
        const childName = Object.keys(parent)[Object.keys(parent).length - 1]
        if (!commandNames[`${key.toUpperCase()}_${childName.toUpperCase()}`]) commandNames[`${key.toUpperCase()}_${childName.toUpperCase()}`] = [childName]
        commandNames[`${key.toUpperCase()}_${childName.toUpperCase()}`].push(a);

    }
}

let file = `
// This file was autogenerated by the genConstants.js script.
// DO NOT MODIFY.

export const CommandNames = ${JSON.stringify(commandNames, null, 4)};
`;

fs.writeFile(join(__dirname, "..", "src", "constants", "commandNames.ts"), file)
    .then(() => console.log("Successfully Generated!"));
